### ISSUE TITLE
use video player in listview fast scrolling error

### ISSUE THREAD

**Issue by getpu** [rvamsikrishna/inview_notifier_list#25]

**Comment by getpu** [comment]
E/ACodec  (22100): signalError(omxError 0x80001001, internalError -19)
E/ACodec  (22100): Error occurred while disabling the output port
E/MediaCodec(22100): Codec reported err 0xffffffed, actionCode 0, while in state 6
D/SurfaceUtils(22100): disconnecting from surface 0x718dc0f010, reason disconnectFromSurface
E/ExoPlayerImplInternal(22100): Playback error
E/ExoPlayerImplInternal(22100):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [1080, 1920, 30.0], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal(22100):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
E/ExoPlayerImplInternal(22100):       at android.os.Handler.dispatchMessage(Handler.java:108)
E/ExoPlayerImplInternal(22100):       at android.os.Looper.loop(Looper.java:216)
E/ExoPlayerImplInternal(22100):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(22100):   Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.hisi.video.decoder.avc
E/ExoPlayerImplInternal(22100):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1377)
E/ExoPlayerImplInternal(22100):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:872)
E/ExoPlayerImplInternal(22100):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
E/ExoPlayerImplInternal(22100):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
E/ExoPlayerImplInternal(22100):       ... 3 more
E/ExoPlayerImplInternal(22100):   Caused by: java.lang.IllegalStateException
E/ExoPlayerImplInternal(22100):       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/ExoPlayerImplInternal(22100):       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2705)
E/ExoPlayerImplInternal(22100):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:58)
E/ExoPlayerImplInternal(22100):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1774)
E/ExoPlayerImplInternal(22100):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:857)
E/ExoPlayerImplInternal(22100):       ... 5 more
E/ExoPlayerImplInternal(22100): Disable failed.
E/ExoPlayerImplInternal(22100):   java.lang.IllegalStateException
E/ExoPlayerImplInternal(22100):       at android.media.MediaCodec.native_flush(Native Method)
E/ExoPlayerImplInternal(22100):       at android.media.MediaCodec.flush(MediaCodec.java:2138)
E/ExoPlayerImplInternal(22100):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:81)
E/ExoPlayerImplInternal(22100):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:914)
E/ExoPlayerImplInternal(22100):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:773)
E/ExoPlayerImplInternal(22100):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:454)
E/ExoPlayerImplInternal(22100):       at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:175)
E/ExoPlayerImplInternal(22100):       at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1507)
E/ExoPlayerImplInternal(22100):       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1254)
E/ExoPlayerImplInternal(22100):       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1218)
E/ExoPlayerImplInternal(22100):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:546)
E/ExoPlayerImplInternal(22100):       at android.os.Handler.dispatchMessage(Handler.java:108)
E/ExoPlayerImplInternal(22100):       at android.os.Looper.loop(Looper.java:216)
E/ExoPlayerImplInternal(22100):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/LocationManager(22100): thread is not runable, msg ignore, state:WAITING, pkg:com.zhaohazi.job
E/LocationManager(22100): thread is not runable, msg ignore, state:WAITING, pkg:com.zhaohazi.job
E/LocationManager(22100): thread is not runable, msg ignore, state:WAITING, pkg:com.zhaohazi.job
I/ACodec  (22100): [OMX.hisi.video.decoder.avc] forcing the release of codec


has the great god ever met the same problem, can you help me???
